- code/services/PurchaseService.php
Some gateways require more data than just amount and currency (e.g. SagePay Server requires transactionId and transactionReference), but `PaymentGatewayController` doesn’t pass any gateway data at all. This extension hook allows `$gatewaydata` to be updated in an extension.
> NEW: Extension point for extra data to complete purchases

- tests/payment.yml
I was scanning through repos I already had copies of for this - tabs aren’t valid for any of the YAML spec versions, and will trigger errors in SilverStripe 4+ (#4591)
One less upgrade pain if a 4.0-compatible version of this module comes around :)
> Fix YAML indentation

- code/model/Payment.php
Updated search-context and summary_fields to include translated values as well.
This fixes #88, but still has the problem described in #90
> Provide an accessor for translated status value.

- code/model/Payment.php
Currently, it causes ModelAdmin to throw an error. Additionally, filtering by one specific date is not very useful. Filtering by a date-range would be better.
> Remove `Created` field from payment-admin filter dialogue.

- README.md
- code/model/GatewayInfo.php
- code/services/PaymentService.php
- code/services/PurchaseService.php
- docs/en/PayPalExpressSetup.md
- docs/en/index.md
- tests/PaymentTest.php
- tests/PurchaseServiceTest.php
This means Payment should only configure the `allowed_gateways`.
Gateway configuration should go into `GatewayInfo`.
Added deprecation warnings. Updated docs and tests.
> Deprecate the old config API.

- code/PaymentGatewayController.php
- code/extensions/Payable.php
- tests/BasePurchaseServiceTest.php
Fix issue where an offsite-payment form would return but payment was already marked complete due to async notification.
Added unit-test to check for above issue.
Added helper method to detect pending payments on `Payable`
> Improve integration with async gateways

- .travis.yml
- README.md
- code/GatewayInfo.php
- docs/en/index.md
- tests/GatewayInfoTest.php
Added information about gateway naming.
"Manual" Gateway is no longer a default setting (updated Docs, GatewayInfo and Unit-Test).
Removed testing against SilverStripe master branch, as this interferes with the stricter version constraint in composer.json (modules standard).
Addresses #111 and #65
> Updated documentation.

- README.md
- code/GatewayInfo.php
- code/Service/CaptureService.php
- code/model/Payment.php
- tests/CaptureServiceTest.php
- tests/GatewayInfoTest.php
- tests/RefundServiceTest.php
Implemented distinction between "partial" and "multiple" partial payments (for capture and refunds).
Changed how excess payments are stored.
Updated documentation and unit-tests.
> Multiple and single partial payments.

- README.md
As `->write()` returns the Payment ID rather than the instance inself..
> ->write() should be called independent of creating the payment object

- _config/rename.yml
- code/GatewayFieldsFactory.php
- tests/GatewayFieldsFactoryTest.php
Field renaming support :)
Let me know what you think
> A more versatile solution to field naming

- code/GatewayFieldsFactory.php
- Added default empty values to startYear, startMonth, expiryYear and expiryMonth with translatable strings
- Implemented fix provided by OP at #145
> Fixes #145, Resolves #147

- code/GatewayFieldsFactory.php
- tests/GatewayFieldsFactoryTest.php
Improved unit-tests for field-renaming.
> Fix issue when trying to look up a field that doesn’t occur in the rename-map

- _config/routes.yml
- code/Exception/InvalidPaymentIntentException.php
- code/Exception/InvalidServiceResponseException.php
- code/PaymentGatewayController.php
- code/Service/PaymentService.php
- tests/PaymentModelTest.php
This is where I have gotten so far with static URL's. It still requires the developer to extend the `PaymentGatewayController` to analyse the request and find a payment identifier.
The example I have below is a fairly basic test that works with Barclays EPDQ:
````
class AppPaymentGatewayControllerExtension extends Extension
{
/**
* Update the payment identifier from the gateway.
*
* @param string $ident the current ident
* @param SS_HTTPRequest $request
* @param string $gateway
* @return void
*/
public function updateIdentifierFromRequest(&$ident, $request, $gateway)
{
if ($gateway == "BarclaysEpdq_Essential") {
$order = Order::get()->find("OrderNumber", $request->postVars("orderID"));
if ($order && $order->Payments()->exists()) {
$payment = $order->Payments()->first();
$ident = …
```
> Initial work on support for static callback endpoints 

- docs/en/TestPayments.md
Debugging the issue with omnipay/dummy made me realize there are no dedicate docs for testing the payment process. I think most of this info is already scattered through the existing docs, but I was thinking some dedicated docs might be more new user friendly?
> Add dedicated docs for testing the payment process

- .travis.yml
- src/GatewayInfo.php
- tests/CreateCardServiceTest.php
- tests/GatewayFieldsFactoryTest.php
Fix unit-tests for changes that happened in the Dummy gateway.
> Make gatewayinfo respect `false` settings on `is_offsite`.

- .gitignore
- composer.json
- src/Admin/PaymentDevelopmentAdmin.php
- src/Extensions/Payable.php
- src/Extensions/SagePayExtension.php
- src/Helper/PaymentMath.php
- src/Model/Payment.php
- src/Model/message/GatewayMessage.php
- src/Model/message/PaymentMessage.php
- src/Service/CaptureService.php
- src/Service/CreateCardService.php
- src/Service/NotificationCompleteService.php
- src/Service/PaymentService.php
- src/Service/RefundService.php
- tests/PaymentTest.php
- tests/Service/TestGatewayFactory.php
There is minimal user exposed change in the API. Majority of change is in how gateways internally handle sending requests (via `ClientInterface`, rather than an explicit dependency on Guzzle).
Unfortunately, there is currently a failing test due to a stray reference to Guzzle in the `omnipay/paymentexpress` gateway package. All tests pass once this is resolved - thephpleague/omnipay-paymentexpress#50, thephpleague/omnipay-paymentexpress#51
Resolves #196
> Support Omnipay v3, as Omnipay v2 hasn't seen active development since 2016

- src/Model/Payment.php
- tests/PaymentModelTest.php
- tests/Service/TestRandomGenerator.php
- Resolves #142
- Fixes bug in generation that allowed duplicate identifiers
- Adds tests for the above two points
- Adds unique index to `Identifier` column to prevent future issues
> Make payment identifier length configurable - globally / per gateway

- src/Model/Payment.php
can't send a null/empty value for localisation
> prevent death on singletons & summary fields

- .upgrade.yml
The silvershop/core module defines a `PaymentForm` class ([source](https://github.com/silvershop/silvershop-core/blob/master/src/Forms/PaymentForm.php)), but this module doesn't.
Having this class listed here means that the Silverstripe 4 upgrader tool complains about it: `Config option PaymentForm is defined with different values in multiple files`
> PaymentForm is not an OmniPay class

- _config/legacy.yml
`GatewayRequestMessage: SilverStripe\Omnipay\Model\Message\GatewayRequestMessage` is listed twice.  Removed top one.  Thanks.
> Updated legacy.yml

- src/Extensions/SagePayExtension.php
Looks like the omnipay SagePay driver has made some changes from v2 to v3. This PR updates the Sagepay extension to bring it inline with v3.
> Update SagePay inline with Omnipay 3

- _config/logging.yml
- docs/en/Logging.md
- src/Service/PaymentService.php
Fixes #226. It’s currently not possible to disable the `logToFile()` method without also disabling logging any exceptions which arise, which is obviously not great as they’ll then go un-reported.
This should be backward compatible, as the new `exceptionLogger` will just default to using the existing `SilverStripe\Omnipay\Logger` service config.
> NEW: Allow logging exceptions separately to non-fatal errors (fixes #226)

- src/Helper/ErrorHandling.php
- src/Helper/Logging.php
Something I overlooked in https://github.com/silverstripe/silverstripe-omnipay/pull/229. `Logging::getLogger()` uses the default logging service, `SilverStripe\Omnipay\Logger`. If that has been set to a `NullLogger` as per the instructions in added #229, then exceptions thrown during `safeExtend()` can be swallowed in live mode.
This change ensures that if a separate logger is set up for fatal errors (as described in #229), it will be used by `safeExtend()` and `safeguard()` so that exceptions can still be logged. As per the other pull request, if no separate Injector service has been set up for `SilverStripe\Omnipay\ExceptionLogger` then it inherits from `SilverStripe\Omnipay\Logger` instead: 
https://github.com/silverstripe/silverstripe-omnipay/blob/a44ee690f30ab2ab1da4834fecb1b6b7d91ff7 …
> Fix issue where exceptions triggered by extensions could be silently swallowed

- src/GatewayInfo.php
Hey,
Previously it'd fail with "ERROR [User Error]: Uncaught Error: Function name must be a string", use (&$convertConstants) must be used for anonymous recursive functions ( https://stackoverflow.com/a/2480242 )
Also the value passed in recursively is $config, which makes it an infinite loop. I changed this to be $value instead which makes it work.
Tom
> Anonymous recursive function requires use () to work & changed var passed into it to avoid infinite loop
