silverstripe/silverstripe-omnipay

- lang/en.yml
- tests/PaymentModelTest.php
Include all the official Omnipay 2.x gateways and CreditCard Brands.
Fixes #89
> Add an *en* locale file for translations.

- code/services/PaymentService.php
- code/services/PurchaseService.php
- tests/PaymentTest.php
- tests/PurchaseServiceTest.php
Also added hook for updating data sent to Omnipay (via extension on PurchaseService)
> Added support for using token instead of card

- code/services/PurchaseService.php
> Fixing PurchaseService, so that it also works with Manual Gateway.

- code/model/Payment.php
- lang/en.yml
- tests/PaymentModelTest.php
Added unit-tests to cover different title-scenarios.
Fixes #96
> Make payment title locale-aware through a title-template.

- code/model/Payment.php
Ah, also changed Varchar length of some DB fields. Since the Gateway could also be a fully qualified classname, 50 characters seemed a bit restrictive.
> Some minor formatting changes

- README.md
- code/Admin/PaymentAdmin.php
- code/GatewayFieldsFactory.php
- code/GatewayInfo.php
- code/PaymentGatewayController.php
- code/model/Payment.php
- lang/en.yml
- tests/GatewayInfoTest.php
- tests/PaymentModelTest.php
Rename them to CamelCase (where applicable) and remove redundant translations.
> Improve translation keys. 

- code/GatewayInfo.php
- code/PaymentGatewayController.php
- code/Service/PaymentService.php
- code/Service/PurchaseService.php
- tests/GridField/GridFieldPaymentActionsTest.php
- tests/GridField/GridFieldTestPayments.yml
- tests/PayableTest.php
- tests/PayableTest.yml
Added unit-tests for Payable.
Added unit-tests for the Payment GridFieldActions
Exclude deprecated methods from code-coverage.
> Improve Unit-Tests

- code/Admin/PaymentDevelopmentAdmin.php
- tests/PayableTest.php
- tests/PaymentTest.php
Disable payment file-logging for unit-tests.
> Fix and improve output of `PaymentDevelopmentAdmin`.

- code/Service/CaptureService.php
- code/Service/RefundService.php
- code/model/Payment.php
- lang/en.yml
- tests/CaptureServiceTest.php
- tests/PaymentModelTest.php
- tests/PaymentTest.php
- tests/RefundServiceTest.php
- tests/VoidServiceTest.php
Added translation keys.
Updated unit-tests.
> Added permissions for refund/capture and void.

- code/GatewayFieldsFactory.php
- tests/GatewayFieldsFactoryTest.php
Allow `null` value for the Gateway.
Added unit-tests.
> Added namespace to GatewayFieldsFactory.

- code/Service/PaymentService.php
This is useful to get the payment in some of the hooks.
> Add an accessor to get the payment from a PaymentService.

- _config/services.yml
- code/PaymentGatewayController.php
- code/Service/CreateCardService.php
- code/Service/ServiceFactory.php
- code/model/Payment.php
- code/model/messaging/CreateCardMessages.php
- tests/CreateCardServiceTest.php
- tests/PaymentTest.php
- tests/PaymentTestExtensions.php
- tests/payment.yml
Implement the create card service for gateways which support it.
Tested with DPS PxPay
Relates to #158
> Implement create card service

- code/extensions/SagePayExtension.php
Providing an extension to others have less of an issue with Sagepay #159
> Adding SagePay Extension

- code/extensions/WorldPayResponseExtension.php
- docs/en/WorldPaySetup.md
- templates/WorldPayCallback.ss
I have added the extension file, a simple template and some docs explaining how to use the WorldPay extension.
> Added WorldPayExtension

- README.md
- docs/en/Configuration.md
- docs/en/GettingStarted.md
I have tried to break out some of the longer parts of the Readme into dedicated documentation pages.
I also tried to plug a few holes in the documentation around getting started, though you may want to double check you are happy with how this is written?
> Slight documentation audit

- code/extensions/SagePayExtension.php
- Ensure data is only added when the Gateway is actually SagePay
- Also support authorize
- Fixed some typos
> Fix some issues in the SagePay extension.

- src/Model/Payment.php
You missed DropdownField and PartialMatchFilter from the imports, so I have added them.
> Added missed imports

- code/PaymentGatewayController.php
- docs/en/Configuration.md
- docs/en/ExtensionHooks.md
- docs/en/StaticRoutes.md
- tests/PaymentGatewayControllerTest.php
Some more work on the static-endpoint feature.
@mlewis-everley Does that look reasonable? I took your `BarclaysEpdq_Essential` examples for the documentation. I hope that's ok?
> Static route tests and documentation.

- .scrutinizer.yml
- .travis.yml
- README.md
- _config/logging.yml
- composer.json
- docs/en/Configuration.md
- docs/en/Logging.md
- docs/en/ManualPaymentSetup.md
- docs/en/PayPalExpressSetup.md
- src/Extensions/Payable.php
- src/GatewayInfo.php
- src/Helper.php
- src/Model/message/GatewayMessage.php
- src/Service/PaymentService.php
- tests/GatewayFieldsFactoryTest.php
- tests/GatewayInfoTest.php
- tests/PayableTest.php
- tests/PaymentGatewayControllerTest.php
- tests/PaymentModelTest.php
- tests/PaymentTest.php
Raise minimum version of SS4 to 4.0.2 (because of the `table_name` issue)!
> Update logging setup for SS4 (including docs).

- src/Service/VoidService.php
> Add amount and currency to the void params as well.

- docs/en/StaticRoutes.md
$request-: >postVars() doesn't take a param, use $request->postVar('orderItem') instead
> Fix bug in static gateway example

- .travis.yml
- code/GatewayInfo.php
- composer.json
- tests/CreateCardServiceTest.php
- tests/GatewayFieldsFactoryTest.php
> allow false for `is_offsite` param.

- src/PaymentGatewayController.php
> #194 Added Void payment status to intents

- tests/Extensions/ServiceFactoryTestExtensionTwo.php
- tests/ServiceFactoryTest.php
Composer 2.0 complained about PSR-4 loading issues (namespace didn't match folder name)
> Fix namespace Extension -> Extensions

- docs/en/Configuration.md
- docs/en/GettingStarted.md
- docs/en/PayPalExpressSetup.md
- docs/en/StaticRoutes.md
- docs/en/WorldPaySetup.md
- docs/en/index.md
- src/GatewayInfo.php
> Add support for storing credentials in environment variables (closes #209)

- src/Model/Payment.php
> Payment: cast Amount as Currency
